### PR TITLE
Fix failures due to requirement of new `--release` mandatory argument  

### LINKED ISSUE #164: Samba build and integration jobs are failing after addition of `--release` option
Recent [commit](https://github.com/gluster/centosci/commit/3cbdc2802493c7aa284557741cc5cdcde7ee962f) which introduced _--release_ option to `cico` command resulted in different failures:

* [gluster_samba-integration](https://ci.centos.org/job/gluster_samba-integration/649/)
  Errors out due to missing argument to _--release_ option.
* [gluster_samba-build-rpms-cento8-master](https://ci.centos.org/view/Gluster/job/gluster_samba-build-rpms-centos8-master/10/console)
  Fails in package installation as host OS changed from CentOS 7 to 8.

### PR DESCRIPTION
**Pull request by anoopcs9**
See commit messages for more details.

Closes #164

### CODE REVIEW

File: jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh [hunk 1]
```diff
@@ -33,13 +33,15 @@ yum -y install git make rpm-build mock ansible createrepo_c
...
 	qemu-kvm \
-	qemu-kvm-tools \
 	qemu-img \
 	make \
 	ansible \
 	libvirt \
 	libvirt-devel
 
+# rsync is not installed by default on CentOS 8
+[ ${CENTOS_VERSION} = "8" ] && dnf -y install rsync || true
```
Comment (nixpanic) [inline jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh:43]: why the `|| true`? If installing `rsync` fails, will the job not eventually fail either?

File: jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh [hunk 2]
```diff
@@ -60,7 +62,12 @@ then
 	yum -y install "https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.rpm"
 fi
 
-vagrant plugin install vagrant-libvirt
+# Since CentOS 8 is based on Fedora 32, following configuration is required for
+# libvirt plugin installation when upstream rpm is consumed.
+# See bullet point "Fedora 32 + upstream Vagrant:" from https://github.com/vagrant-libvirt/vagrant-libvirt#installation
+[ ${CENTOS_VERSION} = "8" ] && VAGRANT_CONFIG_PARAMS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64" || true
```
Comment (nixpanic) [inline jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh:68]: why the `|| true` here?

File: jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh [hunk 3]
```diff
@@ -60,7 +62,12 @@ then
...
+
+CONFIGURE_ARGS=\"${VAGRANT_CONFIG_PARAMS}\" vagrant plugin install vagrant-libvirt
```
Comment (nixpanic) [inline jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh:70]: Is escaping the `"`'s really needed?

**Review by nixpanic — COMMENTED** [review]
Could you run ` jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh` through `shellcheck` and see if there is anything missing? I expect that all variables need (non-escaped) quoting.

File: jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh (hunk 1 above)
Comment (anoopcs9) [reply jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh:43]: I added `|| true` because if the condition results in _false_ i.e, `CENTOS_VERSION != 8` return value will be 1 which is not what we want as the outcome. Script still needs to continue. But as you mentioned if somehow _rsync_ installation fails, we ignore it and continue as per the above change(but will fail at some other point). What do you suggest here? A clean **if** condition?

File: jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh (hunk 2 above)
Comment (anoopcs9) [reply jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh:68]: Same reasoning as before

File: jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh (hunk 3 above)
Comment (anoopcs9) [reply jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh:70]: Hm..there are two configuration options defined separated with [space].

We could either escape [space] directly within `VAGRANT_CONFIG_PARAMS` or use `export CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64"` to avoid escaping `"`s.

File: jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh (hunk 1 above)
Comment (nixpanic) [reply jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh:43]: ah, right, that seems to be a difference from the usual, more verbose
```shell
if [ ${CENTOS_VERSION} = "8" ]
then
    dnf -y install rsync
fi
```
notation

Maybe phrase the comparing and do it like this:
```shell
# only need to install rsync on CentOS 8 and newer
[ ${CENTOS_VERSION} -le "8" ] || dnf -y install rsync
```

File: jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh (hunk 3 above)
Comment (nixpanic) [reply jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh:70]: I think it works fine if you use
```shell
CONFIGURE_ARGS="${VAGRANT_CONFIG_PARAMS}" vagrant plugin install vagrant-libvirt
```

Comment (anoopcs9) [reply jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh:70]: My bad. You are right.

File: jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh (hunk 1 above)
Comment (anoopcs9) [reply jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh:43]: > `[ ${CENTOS_VERSION} -le "8" ] || dnf -y install rsync`

I hope you meant `lt` and not `le`

**Review by nixpanic — APPROVED** [review]
